name: myenv
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiobotocore==2.26.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aioitertools==0.13.0
      - aiosignal==1.4.0
      - alembic==1.17.2
      - anndata==0.12.6
      - annotated-types==0.7.0
      - anyio==4.12.0
      - array-api-compat==1.12.0
      - attrs==25.4.0
      - bio==1.8.1
      - biopython==1.86
      - biothings-client==0.4.1
      - botocore==1.41.5
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorcet==3.1.0
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - dask==2024.11.2
      - dask-expr==1.1.19
      - dask-image==2025.11.0
      - datashader==0.18.2
      - docrep==0.3.2
      - donfig==0.8.1.post1
      - filelock==3.20.0
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - geopandas==1.1.1
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-crc32c==1.7.1
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.72.0
      - gprofiler-official==1.0.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - idna==3.11
      - imagecodecs==2025.11.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - inflect==7.5.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - legacy-api-wrap==1.5
      - llvmlite==0.46.0
      - locket==1.0.0
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-scalebar==0.9.0
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multipledispatch==1.0.0
      - multiscale-spatial-image==2.0.3
      - mygene==3.2.2
      - natsort==8.4.0
      - networkx==3.6.1
      - numba==0.63.0
      - numcodecs==0.16.5
      - numpy==2.3.5
      - ome-zarr==0.12.2
      - omnipath==1.0.12
      - optuna==4.6.0
      - packaging==25.0
      - pandas==2.3.3
      - param==2.3.1
      - partd==1.4.2
      - pathlib-abc==0.5.2
      - patsy==1.0.2
      - pillow==12.0.0
      - pims==0.7
      - platformdirs==4.5.1
      - pooch==1.8.2
      - pot==0.9.6.post1
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyct==0.6.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyg-lib==0.4.0+pt23
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyogrio==0.12.1
      - pyparsing==3.2.5
      - pyproj==3.7.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - rsa==4.9.1
      - s3fs==2025.12.0
      - scanpy==1.11.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - session-info2==0.2.3
      - shapely==2.1.2
      - six==1.17.0
      - slicerator==1.1.0
      - spatial-image==1.2.3
      - spatialdata==0.6.1
      - spatialdata-plot==0.2.13
      - sqlalchemy==2.0.45
      - squidpy==1.7.0
      - statsmodels==0.14.6
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - toolz==1.1.0
      - torch==2.3.0
      - torch-cluster==1.6.3
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2
      - torchaudio==2.3.0
      - torchvision==0.18.0
      - tqdm==4.67.1
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - universal-pathlib==0.3.7
      - uritemplate==4.2.0
      - urllib3==2.6.1
      - validators==0.35.0
      - wrapt==1.17.3
      - xarray==2025.12.0
      - xarray-dataclass==3.0.0
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zarr==3.1.5
      - zipp==3.23.0
prefix: /opt/anaconda3/envs/myenv
